// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jbfzppremfkwqonswqmp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpiZnpwcHJlbWZrd3FvbnN3cW1wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0NTEzNzEsImV4cCI6MjA3MjAyNzM3MX0.ZRwCadOYJ2oLvd-6TBQjS5R-rP19YnBi01EF4eXVslk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});